
# Generated by Django 5.0.2 on 2024-02-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_proposal_category_proposal_datetime_proposal_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='category',
            field=models.CharField(choices=[('Entered', 'Entered'), ('In progress', 'n progress'), ('Finished', 'Finished'), ('Rejected', 'Rejected')], default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('General', 'General'), ('Classes', 'Classes'), ('Adminstrative', 'Adminstrative'), ('Technical', 'Technical')], default='Entered', max_length=20),
        ),
    ]
