# Generated by Django 5.0.2 on 2024-02-29 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_alter_proposal_category_alter_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Classes', 'Classes'), ('Adminstrative', 'Adminstrative'), ('Technical', 'Technical')], default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('Entered', 'Entered'), ('In progress', 'n progress'), ('Finished', 'Finished'), ('Rejected', 'Rejected')], default='Entered', max_length=20),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='proposals.proposal')),
            ],
        ),
    ]
