# Generated by Django 5.0.2 on 2024-02-29 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_alter_proposal_category_alter_proposal_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='upvotes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_fingerprint', models.CharField(max_length=32)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='proposals.proposal')),
            ],
        ),
    ]
