# Generated by Django 5.0.2 on 2024-02-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_upvote_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='author',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
