# Generated by Django 5.0.3 on 2024-03-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_alter_comment_author_alter_proposal_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upvote',
            old_name='browser_fingerprint',
            new_name='user_id',
        ),
    ]
