# Generated by Django 5.0.3 on 2024-03-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_rename_browser_fingerprint_upvote_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='upvote_count_db',
            field=models.IntegerField(default=0),
        ),
    ]
